// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegurosBlazorApp.Server.Data;

#nullable disable

namespace SegurosBlazorApp.Server.Migrations
{
    [DbContext(typeof(APIcontext))]
    [Migration("20211123040350_tablas1")]
    partial class tablas1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SegurosBlazorApp.Shared.Models.Beneficiario", b =>
                {
                    b.Property<int>("BeneficiarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BeneficiarioId"), 1L, 1);

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("PorcentajeParticipacion")
                        .HasColumnType("int");

                    b.HasKey("BeneficiarioId");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasFilter("[PersonaId] IS NOT NULL");

                    b.ToTable("Beneficiario");
                });

            modelBuilder.Entity("SegurosBlazorApp.Shared.Models.Empleado", b =>
                {
                    b.Property<int>("EmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpleadoId"), 1L, 1);

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoId");

                    b.HasIndex("PersonaId")
                        .IsUnique()
                        .HasFilter("[PersonaId] IS NOT NULL");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("SegurosBlazorApp.Shared.Models.Persona", b =>
                {
                    b.Property<int>("PersonaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaId"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CURP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonaId");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("SegurosBlazorApp.Shared.Models.Beneficiario", b =>
                {
                    b.HasOne("SegurosBlazorApp.Shared.Models.Empleado", "Empleado")
                        .WithMany("Beneficiarios")
                        .HasForeignKey("EmpleadoId");

                    b.HasOne("SegurosBlazorApp.Shared.Models.Persona", "Persona")
                        .WithOne("Beneficiario")
                        .HasForeignKey("SegurosBlazorApp.Shared.Models.Beneficiario", "PersonaId");

                    b.Navigation("Empleado");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SegurosBlazorApp.Shared.Models.Empleado", b =>
                {
                    b.HasOne("SegurosBlazorApp.Shared.Models.Persona", "Persona")
                        .WithOne("Empleado")
                        .HasForeignKey("SegurosBlazorApp.Shared.Models.Empleado", "PersonaId");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("SegurosBlazorApp.Shared.Models.Empleado", b =>
                {
                    b.Navigation("Beneficiarios");
                });

            modelBuilder.Entity("SegurosBlazorApp.Shared.Models.Persona", b =>
                {
                    b.Navigation("Beneficiario");

                    b.Navigation("Empleado");
                });
#pragma warning restore 612, 618
        }
    }
}
